### ISSUE TITLE
不可算だったり単数形と形が同じ名詞のvec変数名、どうするべきか

### ISSUE THREAD

**Issue by smallkirby** [smallkirby/smallkirby#8]
`let cars: Vec<Car> = vec![]` はおかしくないけど、`Vec<Info>`の変数名はどうするべきか。

ちなみにぼくは無理やり `let infos: Vec<Info> = vec![]` にします。

**Comment by cookie-s** [comment]
```
let datas
```

**Comment by smallkirby** [comment]
`val VAR`でいいよ、もう
